import { defineConfig } from 'vitepress'

// VitePress site for @anil-labs/validator. Run `pnpm docs:dev`.
export default defineConfig({
  // '/' for local dev and custom domains; the Pages workflow sets DOCS_BASE to
  // the project-site path (e.g. '/validator/').
  base: process.env.DOCS_BASE ?? '/',
  title: '@anil-labs/validator',
  description: 'An expressive, strictly-typed validation library for TypeScript.',
  lastUpdated: true,
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/introduction' },
      { text: 'Rules', link: '/rules' },
      { text: 'API', link: '/api' },
    ],
    sidebar: {
      // Alphabetical A–Z index for the rules reference page.
      '/rules': [
        { text: '← Back to guide', link: '/guide/introduction' },
        { text: 'All rules', link: '/rules' },
        {
          text: 'A – E',
          collapsed: true,
          items: [
            { text: 'accepted', link: '/rules#accepted' },
            { text: 'accepted_if', link: '/rules#accepted-if' },
            { text: 'active_url', link: '/rules#active-url' },
            { text: 'after / after_or_equal', link: '/rules#after' },
            { text: 'alpha', link: '/rules#alpha' },
            { text: 'alpha_dash', link: '/rules#alpha-dash' },
            { text: 'alpha_num', link: '/rules#alpha-num' },
            { text: 'anyOf', link: '/rules#anyof' },
            { text: 'array', link: '/rules#array' },
            { text: 'ascii', link: '/rules#ascii' },
            { text: 'bail', link: '/rules#bail' },
            { text: 'before / before_or_equal', link: '/rules#before' },
            { text: 'between', link: '/rules#between' },
            { text: 'boolean', link: '/rules#boolean' },
            { text: 'confirmed', link: '/rules#confirmed' },
            { text: 'contains', link: '/rules#contains' },
            { text: 'current_password', link: '/rules#current-password' },
            { text: 'date', link: '/rules#date' },
            { text: 'date_equals', link: '/rules#date-equals' },
            { text: 'date_format', link: '/rules#date-format' },
            { text: 'decimal', link: '/rules#decimal' },
            { text: 'declined', link: '/rules#declined' },
            { text: 'declined_if', link: '/rules#declined-if' },
            { text: 'different', link: '/rules#different' },
            { text: 'digits', link: '/rules#digits' },
            { text: 'digits_between', link: '/rules#digits-between' },
            { text: 'dimensions', link: '/rules#dimensions' },
            { text: 'distinct', link: '/rules#distinct' },
            { text: 'doesnt_contain', link: '/rules#doesnt-contain' },
            { text: 'doesnt_end_with', link: '/rules#doesnt-end-with' },
            { text: 'doesnt_start_with', link: '/rules#doesnt-start-with' },
            { text: 'email', link: '/rules#email' },
            { text: 'encoding', link: '/rules#encoding' },
            { text: 'ends_with', link: '/rules#ends-with' },
            { text: 'enum', link: '/rules#enum' },
            { text: 'exclude', link: '/rules#exclude' },
            { text: 'exclude_if', link: '/rules#exclude_if' },
            { text: 'exclude_unless', link: '/rules#exclude_unless' },
            { text: 'exclude_with', link: '/rules#exclude_with' },
            { text: 'exclude_without', link: '/rules#exclude_without' },
            { text: 'exists', link: '/rules#exists' },
            { text: 'extensions', link: '/rules#extensions' },
          ],
        },
        {
          text: 'F – J',
          collapsed: true,
          items: [
            { text: 'file', link: '/rules#file' },
            { text: 'filled', link: '/rules#filled' },
            { text: 'gt / gte / lt / lte', link: '/rules#gt' },
            { text: 'hex_color', link: '/rules#hex-color' },
            { text: 'image', link: '/rules#image' },
            { text: 'in', link: '/rules#in' },
            { text: 'in_array', link: '/rules#in-array' },
            { text: 'in_array_keys', link: '/rules#in-array-keys' },
            { text: 'integer', link: '/rules#integer' },
            { text: 'ip / ipv4 / ipv6', link: '/rules#ip' },
            { text: 'json', link: '/rules#json' },
          ],
        },
        {
          text: 'K – O',
          collapsed: true,
          items: [
            { text: 'list', link: '/rules#list' },
            { text: 'lowercase / uppercase', link: '/rules#lowercase' },
            { text: 'mac_address', link: '/rules#mac-address' },
            { text: 'max / min', link: '/rules#max' },
            { text: 'max_digits / min_digits', link: '/rules#max_digits' },
            { text: 'mimes', link: '/rules#mimes' },
            { text: 'mimetypes', link: '/rules#mimetypes' },
            { text: 'missing (+ conditional)', link: '/rules#missing' },
            { text: 'multiple_of', link: '/rules#multiple-of' },
            { text: 'not_in', link: '/rules#not-in' },
            { text: 'not_regex', link: '/rules#not-regex' },
            { text: 'nullable', link: '/rules#nullable' },
            { text: 'numeric', link: '/rules#numeric' },
          ],
        },
        {
          text: 'P – T',
          collapsed: true,
          items: [
            { text: 'present (+ conditional)', link: '/rules#present' },
            { text: 'prohibited (+ conditional)', link: '/rules#prohibited' },
            { text: 'prohibits', link: '/rules#prohibits' },
            { text: 'regex', link: '/rules#regex' },
            { text: 'required', link: '/rules#required' },
            { text: 'required_array_keys', link: '/rules#required-array-keys' },
            { text: 'required_if (+ conditional)', link: '/rules#required_if' },
            { text: 'required_with (+ conditional)', link: '/rules#required_with' },
            { text: 'same', link: '/rules#same' },
            { text: 'size', link: '/rules#size' },
            { text: 'sometimes', link: '/rules#sometimes' },
            { text: 'starts_with', link: '/rules#starts-with' },
            { text: 'string', link: '/rules#string' },
            { text: 'timezone', link: '/rules#timezone' },
          ],
        },
        {
          text: 'U – Z',
          collapsed: true,
          items: [
            { text: 'ulid', link: '/rules#ulid' },
            { text: 'unique', link: '/rules#unique' },
            { text: 'url', link: '/rules#url' },
            { text: 'uuid', link: '/rules#uuid' },
          ],
        },
      ],
      '/': [
        {
          text: 'Introduction',
          items: [
            { text: 'What is @anil-labs/validator?', link: '/guide/introduction' },
            { text: 'Installation', link: '/guide/installation' },
            { text: 'Quick start', link: '/guide/quickstart' },
          ],
        },
        {
          text: 'Core concepts',
          items: [
            { text: 'Dataset validation', link: '/guide/dataset-validation' },
            { text: 'Type inference', link: '/guide/type-inference' },
            { text: 'Error messages', link: '/guide/error-messages' },
            { text: 'Working with validated input', link: '/guide/validated-input' },
            { text: 'Conditional rules', link: '/guide/conditional-rules' },
            { text: 'Arrays & nested data', link: '/guide/arrays-and-nesting' },
          ],
        },
        {
          text: 'Recipes',
          items: [
            { text: 'Validating files', link: '/guide/files' },
            { text: 'Validating passwords', link: '/guide/passwords' },
            { text: 'Custom rules', link: '/guide/custom-rules' },
            { text: 'Async & database rules', link: '/guide/async-rules' },
            { text: 'Fluent builder', link: '/guide/fluent-builder' },
          ],
        },
        {
          text: 'Frontend frameworks',
          items: [
            { text: 'Vue', link: '/guide/vue' },
            { text: 'React', link: '/guide/react' },
            { text: 'Svelte', link: '/guide/svelte' },
            { text: 'SolidJS', link: '/guide/solid' },
            { text: 'Angular', link: '/guide/angular' },
          ],
        },
        {
          text: 'Backend frameworks',
          items: [
            { text: 'Overview (Node)', link: '/guide/backend' },
            { text: 'Express', link: '/guide/express' },
            { text: 'Fastify', link: '/guide/fastify' },
            { text: 'NestJS', link: '/guide/nestjs' },
            { text: 'Hono (edge)', link: '/guide/hono' },
          ],
        },
        {
          text: 'Reference',
          items: [
            { text: 'Available rules', link: '/rules' },
            { text: 'API', link: '/api' },
          ],
        },
      ],
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/anilkumarthakur60/validator' }],
    search: { provider: 'local' },
    outline: 'deep',
  },
})
